import type { Livro } from '@/types'

export const livroMilionarioMoraAoLado: Livro =   {
    id: 'milionario-mora-ao-lado',
    titulo: 'O Milionário Mora ao Lado',
    autor: 'Thomas J. Stanley e William D. Danko',
    cor: '#64748B',
    categoria: 'educacao-financeira',
    paraQuem: 'Quem confunde renda alta com riqueza e quer entender o perfil real de quem de fato acumula patrimônio',
    ideias: [
      'Renda não é riqueza: ganhar muito e gastar tudo torna a pessoa um UAW (acumulador abaixo da média) — a única métrica que importa de fato é o patrimônio líquido.',
      'A fórmula PAW/UAW estima o patrimônio esperado multiplicando idade pela renda anual bruta e dividindo por 10 — quem está bem acima desse número acumula bem; quem está bem abaixo, não.',
      'O carro que a pessoa dirige raramente define sua riqueza real: a maioria dos milionários pesquisados compra carros usados e populares, e os mantém por muitos anos.',
      'Rejeitar o consumo de status é decisivo: a pressão social para "manter as aparências" é uma das armadilhas mais eficazes contra a acumulação de patrimônio.',
      'A riqueza é uma habilidade, não uma herança: a maior parte dos milionários pesquisados é de primeira geração — construíram, não herdaram, o próprio patrimônio.',
    ],
    resumoCompleto: [
      {
        secao: 'Capítulo 1 — Conheça o Milionário que Mora ao Lado',
        texto:
          'O primeiro capítulo é, ao mesmo tempo, um choque e uma revelação. Stanley e Danko apresentam o que descobriram após anos de pesquisa: a imagem que a sociedade tem do milionário é uma ficção construída pela mídia, pela publicidade e pelo cinema. O milionário típico não mora em condomínio fechado de luxo, não frequenta clube exclusivo e não ostenta joia cara. Pelo contrário: vive num bairro de classe média, talvez numa casa modesta no mesmo quarteirão que você, dirige um carro com mais de cinco anos de uso, e prefere investir em ação a comprar relógio de ouro. A analogia mais poderosa que os autores usam é a de um iceberg: o que vemos na superfície — o carro importado, a roupa de grife, a casa imponente — é só a pontinha, geralmente financiada por dívida; o que está submerso, invisível aos olhos, é o patrimônio de verdade: investimento, poupança, negócio lucrativo, propriedade que gera renda. O milionário verdadeiro construiu um iceberg gigantesco submerso, enquanto o UAW (Acumulador Deficiente de Riqueza) construiu só a ponta visível, sustentada por empréstimo e parcelamento. Imagine dois vizinhos: um médico ortopedista renomado que ganha R$ 45.000 por mês, mora numa casa de R$ 3 milhões, dirige um utilitário de luxo de R$ 600.000, veste grife e leva a família pra resort de luxo toda temporada; e um dono de pequena distribuidora de material de construção que ganha R$ 18.000 por mês, mora numa casa simples de R$ 450.000, dirige um carro popular de alguns anos de uso e veste roupa de marca comum. Quem é o verdadeiro milionário? Provavelmente o segundo — porque o médico gasta quase tudo o que ganha mantendo o padrão esperado da profissão, enquanto o dono da distribuidora vive com uma fração da renda e investe o resto; ao longo de 25 anos, o primeiro acumula dívida e um patrimônio líquido modesto, o segundo constrói um patrimônio de milhões em investimento, imóvel alugado e participação em negócio. A lição prática é desarmadora na simplicidade: pare de julgar riqueza pelo que você vê — o carro importado pode estar financiado em 72 parcelas, a casa imponente pode ter hipoteca de 30 anos, o relógio de grife pode ter sido parcelado no cartão. O verdadeiro indicador de riqueza não é o que a pessoa consome, é o que ela acumula: some todos os bens e subtraia todas as dívidas — o número que sobra é a única medida real da sua riqueza, não importa se você ganha pouco ou muito por mês. Os autores também distinguem "afluência no balanço patrimonial" (riqueza real, ativo superando passivo) de "afluência na renda" (ganha muito, gasta quase tudo) — a sociedade confunde os dois porque consomem parecido, mas um tem liberdade financeira e o outro só tem a ilusão dela.',
      },
      {
        secao: 'Capítulo 2 — Frugalidade, Frugalidade, Frugalidade',
        texto:
          'Se há um princípio que permeia o livro inteiro como fio condutor, é a frugalidade. Mas cuidado: frugalidade, no vocabulário de Stanley e Danko, não é sinônimo de mesquinhez, avareza ou privação — não é viver como eremita recusando gastar um centavo. É o hábito consciente de gastar menos do que se ganha, diferenciar desejo de necessidade, e entender que cada real gasto em consumo ostensivo é um real que não foi investido no futuro. É a arte de viver bem, muito bem inclusive, sem cair na armadilha do consumismo que devora patrimônio inteiro. Pense na frugalidade como um músculo financeiro: assim como um atleta não precisa treinar 12 horas por dia pra ser campeão — precisa treinar de forma inteligente, consistente e disciplinada —, o acumulador de riqueza não precisa viver na miséria pra enriquecer, precisa exercitar o músculo da frugalidade diariamente, com escolhas pequenas que, compostas ao longo de décadas, geram resultado extraordinário. Um café gourmet de R$ 15 por dia não parece muito, mas R$ 15 por dia durante 250 dias úteis por ano são R$ 3.750 — investidos a uma taxa modesta de 8% ao ano ao longo de 30 anos, esses cafés se transformam em mais de R$ 425.000. Esse é o poder da frugalidade: não é sobre privação, é sobre priorização. Os autores mostram que a grande maioria dos milionários pesquisados nunca pagou mais de US$ 400 por um terno, a maioria compra carro usado (não novo), quase nenhum possui relógio de luxo, preferem restaurante de qualidade a preço justo em vez de restaurante estrelado. Não é falta de recurso — é escolha deliberada, baseada no entendimento de que dinheiro vale mais investido do que consumido. Imagine uma professora universitária de 35 anos ganhando R$ 12.000 por mês: ela poderia alugar apartamento de luxo por R$ 8.000, ter plano de saúde top por R$ 3.000, frequentar academia premium, jantar fora e viajar pra Europa todo ano — gastaria praticamente tudo e teria patrimônio zero. Mas se ela morar num apartamento confortável por R$ 2.500, tiver plano de saúde adequado por R$ 800, cozinhar em casa na maior parte do tempo, viajar mais modestamente nas férias e investir R$ 6.000 por mês, em 20 anos terá acumulado por volta de R$ 3,5 milhões — o suficiente pra viver de renda passiva o resto da vida. A lição prática: faça um diagnóstico dos gastos dos últimos três meses, separe em necessidade essencial, desejo moderado e ostentação pura, e pergunte honestamente quanto da terceira categoria poderia virar investimento.',
      },
      {
        secao: 'Capítulo 3 — Tempo, Energia e Dinheiro',
        texto:
          'Este é um dos capítulos mais reveladores porque desafia uma suposição automática: se eu ganhar mais dinheiro, ficarei mais rico. Stanley e Danko demonstram, com dado empírico robusto, que renda e riqueza são duas variáveis quase independentes — alguém pode ganhar R$ 100.000 por mês e ter patrimônio líquido negativo; outra pessoa pode ganhar R$ 8.000 por mês e ter patrimônio de R$ 5 milhões. A diferença não está em quanto se ganha, mas em como se aloca tempo, energia e dinheiro. Os PAWs (Acumuladores Prodigiosos de Riqueza) gastam, em média, bem mais tempo planejando as próprias finanças do que os UAWs (Acumuladores Deficientes de Riqueza) — não são day traders obcecados por gráfico, dedicam tempo semanal (entre 8 e 10 horas por mês) revisando investimento, analisando despesa, estudando oportunidade de negócio, conversando com contador e assessor financeiro. Os UAWs, por outro lado, passam mais tempo preocupados com dinheiro do que planejando com dinheiro — gastam hora escolhendo carro novo, comparando modelo de celular, pesquisando férias de luxo, mas quase nenhum tempo pensando em como fazer o próprio dinheiro trabalhar. A metáfora dos dois jardineiros ilustra bem: o PAW passa uma hora por dia cuidando da própria horta — regando, podando, protegendo — e ela cresce devagar mas de forma saudável; o UAW passa uma hora por dia admirando a horta do vizinho, reclamando que a própria não cresce, comprando ferramenta cara que nunca usa. No fim do ano, um colhe fartura de vegetal, o outro colhe erva daninha e frustração — o tempo e a energia são os mesmos, a alocação é completamente diferente. Um engenheiro de 42 anos que ganha R$ 25.000 por mês pode ser um UAW clássico: passa 60 horas por ano pesquisando qual carro importado comprar, negociando desconto com concessionária, e acaba comprando um utilitário de R$ 450.000 financiado em 60 parcelas. Um amigo dele, também engenheiro de 42 anos ganhando R$ 5.000 a menos, pode ser um PAW: passa essas mesmas 60 horas por ano estudando fundo de investimento, analisando mercado imobiliário, conversando com o contador sobre estratégia tributária, dirige um carro popular pago à vista. Anos depois, o segundo tem um patrimônio líquido milhões maior que o primeiro, que carrega uma dívida de carro enorme. A lição prática é uma inversão de prioridade: se você passa muito mais tempo consumindo do que planejando, inverta isso — dedique pelo menos algumas horas por semana ao planejamento financeiro ativo, revisando gasto, estudando opção de investimento, tendo conversa estratégica sobre meta financeira.',
      },
      {
        secao: 'Capítulo 4 — Você Não É o Que Você Dirige',
        texto:
          'Nenhum capítulo do livro é mais emblemático que este. "Você não é o que você dirige" é mais que um título — é um manifesto contra a cultura do consumo de status. Stanley e Danko dedicam páginas inteiras a desmontar o mito de que o carro que você dirige reflete seu sucesso, sua inteligência ou seu valor como pessoa. Descobriram que a grande maioria dos milionários pesquisados nunca comprou carro novo — nunca. A idade média dos carros deles era de quatro anos; a maioria comprava veículo usado, de marca popular, e mantinha por longo período. O carro mais comum entre os milionários americanos pesquisados? Uma picape utilitária, nada glamourosa. A razão vai muito além de economia simples: o carro é o ativo de consumo mais depreciativo que a maioria compra na vida — no momento em que sai da concessionária já perde uma fatia grande do valor, e em cinco anos um carro de luxo pode perder a maior parte do valor original. Pra um UAW, o carro é símbolo de status, uma declaração pro mundo de que "chegou lá"; pra um PAW, é ferramenta de transporte, ponto final. Imagine dois carros lado a lado no semáforo: à esquerda, um executivo de 38 anos num utilitário de luxo de R$ 650.000, financiado em 72 parcelas de R$ 9.500; à direita, um empresário de 55 anos num carro popular de 2018, avaliado em R$ 85.000, pago à vista há cinco anos. O executivo está pensando na próxima parcela, no seguro caro, na manutenção de concessionária; o empresário está pensando no dividendo que recebeu da carteira de ações na semana passada, no apartamento que comprou pra alugar, no jantar que vai fazer com a família no fim de semana. Quem está mais rico? Mais livre? Dorme melhor à noite? A resposta é óbvia — mas a sociedade aplaude o do carro caro e ignora o outro; esse é o paradoxo central do capítulo. Os autores chamam de "síndrome de manter as aparências" a pressão social pra consumir conforme a expectativa da profissão, do bairro ou do círculo social — advogado esperado a dirigir carro de luxo, médico esperado a morar em bairro nobre, executivo esperado a frequentar clube exclusivo. Cada real gasto pra impressionar os outros é um real que não foi investido em liberdade financeira — e o pior, os outros nem estão realmente impressionados, estão ocupados demais tentando impressionar você de volta. A lição prática: separe completamente sua identidade dos bens de consumo que possui. Da próxima vez que for comprar um carro, pergunte: "estou comprando isso porque preciso de transporte confiável, ou porque quero que as pessoas na rua me vejam de certa forma?" Se a resposta for a segunda, feche a carteira — o dinheiro economizado pode ser o primeiro tijolo do seu patrimônio.',
      },
      {
        secao: 'Capítulo 5 — O Cuidado Econômico Ambulatorial',
        texto:
          'Este é um dos capítulos mais controversos e, ao mesmo tempo, mais relevantes do livro. Stanley e Danko cunharam o termo "Economic Outpatient Care" (Cuidado Econômico Ambulatorial, ou EOC) pra descrever o fenômeno de pais financeiramente saudáveis que subsidiam sistematicamente o estilo de vida de filhos adultos. Não se trata de ajudar um filho numa emergência médica ou dar uma força durante desemprego transitório — o EOC é um padrão crônico de transferência de recurso dos pais pros filhos adultos, que permite que eles vivam acima das próprias possibilidades. A analogia com cuidado médico ambulatorial é intencional: assim como um paciente que depende de visita regular ao médico pra manter a saúde nunca desenvolve hábito saudável por conta própria, o filho adulto que recebe EOC depende dos pais pra manter o padrão de vida, sem nunca desenvolver disciplina financeira própria — os pais pagam a faculdade do neto, financiam a reforma do apartamento do filho, cobrem a férias da família, pagam o plano de saúde dos netos, até ajudam com a parcela do carro. O resultado: o filho nunca aprende a nadar porque os pais nunca deixam a água passar da cintura dele. Os dados da pesquisa são alarmantes: filhos que recebem EOC regularmente têm, em média, bem menos patrimônio líquido do que filhos de pais com renda parecida que não recebem esse tipo de ajuda — ou seja, a ajuda financeira dos pais não apenas não ajuda, ela prejudica ativamente a capacidade do filho de acumular riqueza, porque ele internaliza a mensagem de que "sempre haverá alguém pra me salvar", o que elimina o incentivo pra poupar, investir e viver dentro dos próprios meios. Além disso, o EOC cria dependência psicológica que pode durar décadas — filho de 40, 50 anos ainda recebendo "ajudinha" de pai de 70, 80 anos. A lição prática é delicada porque envolve amor familiar, mas inquestionavelmente importante: os melhores pais não são os que dão dinheiro aos filhos adultos, são os que ensinam os filhos a ganhar e gerenciar o próprio dinheiro. Se você é pai e está considerando ajudar financeiramente um filho adulto, pergunte-se: essa ajuda é realmente necessária ou o filho poderia resolver sozinho? Está ensinando independência ou reforçando dependência? Estou sacrificando meu próprio futuro financeiro pra manter o estilo de vida do meu filho? Se a resposta pra qualquer uma for preocupante, a ajuda deve ser repensada — o maior legado que um pai pode deixar não é dinheiro, é a capacidade do filho de gerar e gerenciar o próprio dinheiro.',
      },
      {
        secao: 'Capítulo 6 — A Riqueza na Próxima Geração',
        texto:
          'Continuação lógica do capítulo anterior, este aborda um dos fenômenos mais tristes e previsíveis da história econômica: a destruição geracional da riqueza. Stanley e Danko descrevem um padrão que se repete com regularidade assustadora em família de toda origem e cultura, chamado de "shirtsleeves to shirtsleeves in three generations" — "de mangas de camisa a mangas de camisa em três gerações". A primeira geração começa com as mangas arregaçadas, trabalhando duro pra construir riqueza. A segunda, que cresceu vendo os pais trabalharem, mantém o negócio mas já começa a gastar mais. A terceira, que nunca viu o trabalho árduo da primeira, dilapida tudo e volta a ter as mangas arregaçadas — mas agora sem nada. Os autores identificaram que a grande maioria dos milionários pesquisados — cerca de 80% — é de primeira geração: não herdaram fortuna, construíram com as próprias mãos, contrariando a crença popular de que riqueza se passa de pai pra filho como uma coroa. Na verdade, riqueza herdada tem taxa de sobrevivência ruim: segundo a pesquisa, 70% das famílias ricas perdem a riqueza na segunda geração, e 90% na terceira — o que significa que, sendo você um milionário de primeira geração, há só 10% de chance de seus netos ainda serem milionários. A metáfora da árvore explica bem: a primeira geração planta a semente, rega todo dia, protege da praga e espera pacientemente; a segunda herda a árvore madura e começa a colher fruto, mas também a podar galho pra fazer móvel, vender madeira, negligenciar a rega; a terceira herda um tronco podre, sem fruto, sem raiz — não sabe plantar porque nunca viu o avô plantar, não sabe regar porque nunca viu o pai regar, não sabe esperar porque cresceu em mundo de gratificação instantânea. Vale a história de um imigrante que chegou numa cidade brasileira décadas atrás só com uma mala e determinação, começou como ajudante e aos 50 anos já tinha uma pequena construtora, trabalhando 14 horas por dia e vivendo modestamente — aos 70, deixou um patrimônio de R$ 15 milhões pros dois filhos. O filho mais velho herdou a construtora, trabalhava mas já não com a mesma intensidade, comprou carro de luxo, viajou internacionalmente, expandiu a empresa com dívida — aos 60, deixou R$ 8 milhões pros três filhos, metade do que herdou. O neto mais velho vendeu sua parte, comprou apartamento fora do país, viveu de renda — em 10 anos o dinheiro acabou, e aos 45 estava desempregado e endividado. A fortuna do avô, construída com 50 anos de suor, foi reduzida a pó em duas gerações. A lição prática: riqueza não é bem que se transmite, é habilidade que se ensina — envolver os filhos nas decisões financeiras da família desde cedo, exigir que trabalhem pelas próprias conquistas, ensinar a fórmula de avaliação de progresso financeiro, e deixar a maior parte do patrimônio pra instituição de caridade ou fundação, com o suficiente pros filhos como "ponto de partida", não "ponto de chegada".',
      },
      {
        secao: 'Capítulo 7 — Encontre Seu Nicho',
        texto:
          'O sétimo e último capítulo principal aborda uma das descobertas mais surpreendentes da pesquisa: a relação entre profissão e acumulação de riqueza. Contra toda expectativa, os autores descobriram que as profissões mais prestigiosas e bem remuneradas — médico, advogado, dentista, executivo corporativo — têm proporção desproporcionalmente alta de UAWs. Já profissões consideradas "comuns" ou "modestas" — dono de pequeno negócio, empreiteiro, corretor de imóvel, vendedor, contador independente — têm proporção muito maior de PAWs. A resposta está em três fatores interligados: o atraso na acumulação causado pela longa formação acadêmica, a pressão social pra manter padrão de vida compatível com a profissão, e a falta de controle sobre a própria renda. Um médico, por exemplo, gasta entre 10 e 15 anos em formação (faculdade, residência, especialização) sem acumular riqueza — só dívida ou anos de renda perdida; quando finalmente começa a ganhar bem, já está bem atrasado na corrida da acumulação, e a sociedade espera que more em bairro nobre, dirija carro de luxo, frequente clube exclusivo — cada "requisito" consome fatia enorme da renda, e um médico assalariado tem pouco controle sobre quanto ganha. Compare com o dono de uma pequena distribuidora de material de construção que começou aos 20 anos como ajudante, comprou o primeiro caminhão usado aos 25, e aos 35 já tinha uma frota e uma dúzia de funcionários — nunca fez faculdade, não tem dívida de estudante, vive num bairro de classe média onde ninguém espera ostentação, tem custo de vida baixo e renda controlada por ele mesmo, reinvestindo o lucro no negócio. Aos 55, seu patrimônio supera o de muitos médicos e advogados da mesma idade — não porque é mais inteligente ou talentoso, mas porque escolheu uma profissão onde a relação entre esforço, controle e acumulação é mais favorável. Os autores não estão dizendo que você deve abandonar a carreira; estão dizendo que a escolha da profissão é uma das decisões mais importantes da vida financeira, e que "prestígio" e "renda alta" não são sinônimos de "acumulação de riqueza". A profissão ideal tem poucos concorrentes mas gera lucro alto, permite amar o que se faz, oferece controle sobre a própria renda, e não impõe padrão de vida caro como obrigação social. A lição prática final: pergunte-se se você ama o que faz, se tem controle sobre sua renda, e se sua profissão te obriga a gastar mais do que gostaria só pra "manter as aparências" — não é necessário mudar de profissão, às vezes basta mudar de modelo de trabalho, de assalariado pra autônomo, de empregado pra sócio. Riqueza não é acidente de nascimento nem prêmio de loteria — é escolha diária, uma série de decisões pequenas e aparentemente insignificantes que, compostas ao longo de décadas, se transformam em liberdade financeira.',
      },
    ],
  }
