import type { Livro } from '@/types'

export const livroPaiRicoPaiPobre: Livro =   {
    id: 'pai-rico-pai-pobre',
    titulo: 'Pai Rico, Pai Pobre',
    autor: 'Robert Kiyosaki',
    cor: '#FFC93C',
    categoria: 'educacao-financeira',
    paraQuem: 'Quem está começando e precisa mudar a forma de pensar sobre dinheiro antes de aprender técnica',
    ideias: [
      'A diferença entre ativo e passivo é a base de tudo: ativo coloca dinheiro no seu bolso, passivo tira — e a casa própria que você mora, sem gerar renda, é passivo, não ativo.',
      'Os ricos não trabalham pelo dinheiro, fazem o dinheiro trabalhar para eles — construindo fontes de renda que não dependem do seu tempo direto.',
      "A 'Corrida dos Ratos' é o ciclo de ganhar mais e gastar mais na mesma proporção, mantendo a pessoa presa financeiramente mesmo com salário alto.",
      'Alfabetização financeira é tão importante quanto alfabetização de leitura — saber ler um balanço patrimonial muda decisões de vida inteiras.',
      "Pergunte 'o que posso fazer para comprar isso' em vez de dizer 'não posso comprar isso' — a primeira frase mantém sua mente ativa buscando soluções.",
    ],
    resumoCompleto: [
      {
        secao: 'Introdução — Duas Filosofias, Dois Destinos',
        texto:
          '"Pai Rico, Pai Pobre" não é um manual de investimentos, nem um guia técnico sobre como escolher ações ou montar uma carteira diversificada. Também não é um livro de autoajuda prometendo fórmula mágica pra enriquecer da noite pro dia. O que ele realmente é — e isso o torna tão poderoso — é um livro sobre mentalidade financeira, uma espécie de alfabetização econômica escrita em linguagem acessível, quase como uma conversa entre amigos numa mesa de bar. Kiyosaki usa a própria vida como pano de fundo: enquanto o pai biológico (o "Pai Pobre"), um homem altamente instruído com Ph.D. e respeitado no meio acadêmico, acreditava na segurança do emprego, no estudo pra conseguir bom salário e na estabilidade como meta suprema, o pai de seu melhor amigo Mike (o "Pai Rico"), sem diploma mas dono de um império empresarial no Havaí, ensinava que a verdadeira segurança vem da capacidade de fazer o dinheiro trabalhar por você, não o contrário. A tese central: a diferença entre quem enriquece e quem fica preso na escassez não está no salário, na formação acadêmica ou na sorte — está em como cada um pensa sobre dinheiro, trabalho e ativos. O livro é estruturado em seis lições principais, cada uma desdobrada em capítulos que misturam narrativa autobiográfica com conceito financeiro fundamental.',
      },
      {
        secao: 'Capítulo 1 — Os Ricos Não Trabalham por Dinheiro: o Dinheiro Trabalha para Eles',
        texto:
          'A primeira lição de Kiyosaki é, ao mesmo tempo, a mais simples e a mais difícil de aceitar: a maioria das pessoas passa a vida inteira correndo atrás do dinheiro, quando deveria estar construindo máquinas que produzem dinheiro automaticamente. Pense na diferença entre carregar água de um poço todos os dias (trabalho ativo) e construir um sistema de encanamento que leva água até a casa sem esforço (trabalho passivo). O problema não é que as pessoas sejam preguiçosas — é que foram ensinadas, desde crianças, a acreditar que a única forma legítima de ganhar dinheiro é trocar hora de trabalho por salário. Essa crença, embora socialmente respeitável, mantém milhões de pessoas presas na chamada "corrida dos ratos". Para ilustrar, imagine duas pessoas: João, engenheiro, ganha R$ 15.000 por mês numa multinacional; Maria, dona de um pequeno prédio comercial, recebe R$ 8.000 por mês de aluguéis. João trabalha 50 horas semanais, viaja constantemente, sofre com estresse, e se for demitido amanhã sua renda cai a zero. Maria pode estar viajando pela Europa, dormindo ou cuidando dos netos — os aluguéis continuam entrando na conta dela. João não é burro nem Maria mais inteligente: ele está do lado errado da equação, trabalha pelo dinheiro, enquanto ela fez o dinheiro trabalhar por ela. A lição prática: trate cada real que entra na conta como um "soldado" que pode ser enviado pra trabalhar no seu lugar. Em vez de um carro zero parcelado em 60 vezes que custa R$ 2.000 por mês e só gera despesa, usar esse mesmo valor pra comprar cotas de um fundo imobiliário que paga dividendo mensal. Com o tempo, esses "soldados" se multiplicam até gerar renda suficiente pra cobrir todas as despesas — e é nesse momento que se alcança a independência financeira. A analogia do Banco Imobiliário (Monopoly) resume o princípio: compre propriedades que geram renda, evite gastar em coisas que não produzem nada, e deixe que o tabuleiro pague por você. A vida real funciona assim — a diferença é que a maioria nunca aprende as regras do jogo.',
      },
      {
        secao: 'Capítulo 2 — Por Que a Escola Não Ensina Educação Financeira?',
        texto:
          'A segunda lição é uma denúncia incisiva contra o sistema educacional tradicional. Por que se passam doze anos na escola aprendendo a resolver equação de segundo grau, memorizar a tabela periódica e analisar poesia, mas ninguém ensina a ler um extrato bancário, entender a diferença entre juros simples e compostos, ou montar um fluxo de caixa pessoal? A resposta, segundo Kiyosaki, é perturbadora: o sistema não foi projetado pra criar pessoas financeiramente independentes, mas pra criar funcionários obedientes, consumidores fiéis e contribuintes previsíveis. Pense num jovem de 18 anos recém-formado no ensino médio: sabe calcular a área de um triângulo, mas não sabe como funciona um consignado; pode citar presidentes em ordem cronológica, mas não entende como se calcula uma aposentadoria. Foi ensinado a buscar diploma universitário como amuleto de proteção, mas ninguém explicou que diploma sozinho não gera renda — só aumenta a chance de conseguir emprego melhor pago, o que sem educação financeira costuma significar apenas dívida maior: carro mais caro, apartamento maior, estilo de vida mais consumista. O ciclo se repete, em escala maior. Kiyosaki conta que aos nove anos ele e Mike tentaram "fabricar dinheiro" derretendo tubo de pasta de dente pra cunhar moeda — ideia infantil, mas reveladora de curiosidade genuína sobre como dinheiro funciona. O pai biológico não soube responder "como fico rico" de forma satisfatória; o pai de Mike se ofereceu pra ensinar, mas com uma condição: os meninos teriam que trabalhar pra ele sem receber nada, só pra aprender. A lição: educação financeira não vem de livro didático ou aula teórica — vem da experiência prática, da tentativa e erro, da observação de como o dinheiro realmente flui no mundo. Não espere que escola, faculdade ou governo ensinem isso: essa responsabilidade é sua. Como dizia o Pai Rico: "O dinheiro é apenas uma ideia. Quanto mais ideias você tiver, mais dinheiro você fará."',
      },
      {
        secao: 'Capítulo 3 — Ativos vs. Passivos: A Diferença que Separa os Ricos dos Pobres',
        texto:
          'Se houvesse apenas um conceito pra gravar pra sempre depois de ler este livro, seria este: a diferença entre ativos e passivos. Kiyosaki define ativo como "algo que coloca dinheiro no seu bolso" e passivo como "algo que tira dinheiro do seu bolso". Parece simples, quase óbvio — e é exatamente por isso que a maioria ignora essa distinção, acumulando passivo achando que constrói patrimônio, enquanto os ricos, silenciosamente, acumulam ativo que gera renda mês após mês. Um exemplo comum: um advogado bem-sucedido compra um apartamento de R$ 800.000 pra morar, com entrada de R$ 200.000 financiando o resto em 30 anos — todo mês desembolsa R$ 4.500 de prestação, mais condomínio, IPTU e manutenção, total de R$ 6.000 saindo do bolso. O gerente do banco chama isso de "o maior ativo" dele. Mas pelo critério do Pai Rico, esse apartamento é um passivo gigantesco: não gera um centavo de renda, pelo contrário, drena R$ 6.000 mensais do fluxo de caixa. Se em vez disso ele tivesse alugado um apartamento parecido por R$ 3.500 e usado os R$ 200.000 de entrada pra comprar um imóvel menor num bairro em expansão, alugando por R$ 2.500, esse imóvel alugado seria um ativo — gera renda. A diferença não está no objeto em si, mas na direção do fluxo de caixa. A lição prática é brutalmente honesta: antes de comprar qualquer coisa, pergunte "isso vai colocar dinheiro no meu bolso ou tirar dinheiro do meu bolso?". Isso não significa nunca comprar passivo — todo mundo precisa de moradia, carro, roupa — significa ter consciência da diferença, e não confundir conforto com investimento, nem justificar carro de luxo dizendo que "é um ativo que valoriza" (exceto raríssima exceção, carro é um dos piores passivos que existem: deprecia rápido, consome combustível, seguro, IPVA e manutenção). Os ricos compram ativo primeiro e usam a renda dele pra pagar pelo passivo; os pobres e a classe média compram passivo primeiro, e passam a vida trabalhando pra pagar por ele. A analogia da árvore frutífera fecha o raciocínio: ativo é como uma muda plantada no quintal — com o tempo, dá fruto sozinha; passivo é como uma cerca de madeira bonita — protege, embeleza, mas nunca produz nada, e ainda apodrece exigindo troca. O rico planta muda. O pobre constrói cerca.',
      },
      {
        secao: 'Capítulo 4 — A História dos Impostos e o Poder das Empresas',
        texto:
          'A quarta lição é uma das mais controversas do livro. Kiyosaki argumenta que o sistema tributário, embora apresentado como ferramenta de justiça social, foi historicamente moldado de forma que corporação e investidor conseguem reduzir legalmente sua carga tributária, enquanto assalariado paga o imposto já descontado na fonte, sem margem de negociação. Pra entender isso, imagine duas pessoas ganhando R$ 10.000 por mês: Ana, designer freelancer que trabalha como pessoa física, e Bruno, dono de uma pequena empresa de tecnologia (pessoa jurídica). Ana recebe os R$ 10.000, paga 27,5% de Imposto de Renda (R$ 2.750) mais INSS (cerca de R$ 1.100), ficando com por volta de R$ 6.150 líquidos — com isso paga aluguel, comida, transporte, e o que sobra investe. Bruno recebe os R$ 10.000 na conta da empresa; antes de pagar imposto, a empresa deduz o que precisa (aluguel do escritório, internet, computador, viagem de negócio, curso de capacitação), deixando um lucro tributável bem menor — sobre isso paga imposto corporativo, geralmente numa alíquota menor que a de pessoa física, e se quiser distribuir esse lucro pra si mesmo, os proventos são isentos de Imposto de Renda no Brasil. O resultado: Bruno, ganhando o mesmo que Ana, paga proporcionalmente menos imposto e ainda tem a empresa como escudo legal. A lição prática não é "sonegue" — isso é ilegal e antiético — é "entenda as regras do jogo e jogue de forma inteligente": estudar os regimes de tributação disponíveis pra empresa (Simples Nacional, Lucro Presumido, Lucro Real), entender dedução fiscal, conhecer investimento isento de Imposto de Renda (como LCI, LCA e alguns fundos imobiliários), e estruturar as próprias atividades pensando em eficiência tributária. Como diz Kiyosaki: "Não é quanto você ganha que importa, é quanto você fica com." E boa parte do que "fica com" depende de quanto se entende sobre imposto.',
      },
      {
        secao: 'Capítulo 5 — Os Ricos Inventam Dinheiro',
        texto:
          'Talvez a lição mais revolucionária de todo o livro. Kiyosaki não fala de falsificação, golpe ou qualquer atividade ilegal — fala de criatividade financeira: a capacidade de enxergar oportunidade onde outros só veem problema, e de transformar ideia em fluxo de renda. Os ricos não esperam que o dinheiro apareça, eles o criam — desenvolvendo um produto novo, encontrando um imóvel subvalorizado pra reformar, criando um curso online, licenciando uma patente, ou simplesmente conectando duas pessoas que precisam uma da outra e cobrando comissão pelo serviço. Considere o caso de um jovem numa cidade do interior de Minas Gerais que percebeu que os produtores rurais da região tinham dificuldade de vender queijo artesanal fora do estado — em vez de só lamentar, ele criou um e-commerce simples, fotografou os produtos, montou um sistema de embalagem com gelo seco pra envio, e começou a vender pra São Paulo e Rio de Janeiro. Em dois anos, faturava R$ 50.000 por mês — não porque herdou dinheiro ou tinha diploma de Harvard, mas porque viu uma necessidade de mercado e criou uma solução. Isso é "inventar dinheiro" no sentido que Kiyosaki propõe: identificar um vazio, preenchê-lo com valor, cobrar pelo valor entregue. A lição prática é desenvolver o que ele chama de "inteligência financeira" — combinação de quatro habilidades: contabilidade (ler número), investimento (estratégia de alocação), compreensão de mercado (oferta e demanda) e direito (proteção jurídica e tributária). Dominando essas quatro áreas, você deixa de ser peão no tabuleiro e vira jogador — consegue olhar pra um imóvel abandonado e ver uma pousada, pra um grupo de gente frustrada com um serviço e ver uma startup, pra uma habilidade que você tem e ver um curso. O dinheiro não é recurso escasso, é consequência de resolver problema: quanto mais problema você resolve, mais dinheiro flui na sua direção. A analogia do agricultor e do cozinheiro fecha o raciocínio: o agricultor planta trigo, colhe e vende o grão por pouco; o cozinheiro compra o trigo, transforma em pão artesanal, e vende por dez vezes o valor. Os ricos são cozinheiros — não se contentam em vender o trigo bruto, criam pão, bolo, massa, cerveja artesanal.',
      },
      {
        secao: 'Capítulo 6 — Trabalhe para Aprender, Não Trabalhe por Dinheiro',
        texto:
          'A sexta lição desafia uma das crenças mais arraigadas da cultura ocidental: a ideia de que o objetivo do trabalho é ganhar dinheiro. O Pai Rico ensinou que essa é uma visão míope — o verdadeiro objetivo do trabalho é aprender: adquirir habilidade que ninguém pode tirar de você, aprender a gerenciar gente, vender, negociar, liderar, resolver problema complexo. O dinheiro é apenas subproduto do aprendizado. Quando você trabalha pra aprender, cada experiência vira investimento em você mesmo; quando trabalha só pelo dinheiro, cada experiência vira transação isolada que não acumula valor ao longo do tempo. Kiyosaki conta que, formado na faculdade, se alistou nos fuzileiros navais dos Estados Unidos — pra muitos parecia desvio insano, mas ele queria aprender a liderar, trabalhar sob pressão, tomar decisão em ambiente caótico. Depois foi trabalhar como vendedor na Xerox — não porque amava fotocopiadora, mas porque queria superar o medo de rejeição e aprender a vender; em pouco tempo virou um dos cinco melhores vendedores da empresa. Só então, com essas habilidades consolidadas, deixou o emprego pra montar o próprio negócio. O dinheiro que deixou de ganhar nos primeiros anos foi, na verdade, o preço de uma educação prática que faculdade nenhuma poderia oferecer. A aplicação prática: ao escolher emprego, pergunte não só "quanto vou ganhar" mas "o que vou aprender" — uma posição que paga R$ 3.000 mas te expõe a todas as áreas de uma empresa (venda, marketing, operação, finanças) pode ser infinitamente mais valiosa do que uma que paga R$ 6.000 mas mantém a mesma tarefa repetitiva por anos. O conhecimento é o único ativo que não deprecia, não pode ser confiscado e não paga imposto. A analogia do especialista e do generalista fecha o capítulo: o especialista é como um médico cardiologista que ganha muito mas só sabe fazer uma coisa — se o mercado pra cardiologista desabar, ele está em apuro; o generalista entende um pouco de contabilidade, marketing, direito, venda — não é o melhor em nenhuma área, mas consegue juntar as peças e criar algo novo. O Pai Rico ensinou Kiyosaki a ser generalista: alguém que sabe o suficiente de cada área pra identificar oportunidade e contratar especialista quando necessário.',
      },
      {
        secao: 'Comece Agora: Dez Passos para Desenvolver seu Poder Financeiro',
        texto:
          'O capítulo final é um chamado à ação. Depois de desmontar crença limitante, explicar ativo e passivo, revelar o segredo dos impostos e mostrar como os ricos inventam dinheiro, Kiyosaki pergunta: e agora, o que você vai fazer com tudo isso? A resposta não pode ser "vou pensar sobre isso" — tem que ser "vou começar agora". Dez passos práticos:',
        lista: [
          'Encontre uma razão maior que a realidade atual — Kiyosaki conta que quando ele e a esposa Kim estavam sem dinheiro, dormindo no banco de trás do carro, a única coisa que os mantinha em pé era a visão de um futuro melhor, o "porquê" de nunca mais depender de emprego.',
          'Escolha diariamente o que colocar no cérebro — ouvir podcast de finanças no trajeto pro trabalho, ler pelo menos um livro por mês, assistir vídeo de investidor experiente.',
          'Escolha os amigos com cuidado — tenha amigo que fala sobre negócio, oportunidade e crescimento, não só futebol e fofoca.',
          'Domine uma fórmula e depois aprenda outra — não fique preso a uma única estratégia de investimento.',
          'Pague-se primeiro — antes de pagar qualquer conta, transfira pelo menos 10% do salário pra investimento.',
          'Pague seus corretores generosamente — bom contador, advogado e consultor são investimento, não despesa; um bom contador pode economizar muito mais do que custa.',
          'Seja um doador generoso — às vezes é preciso trabalhar de graça pra adquirir conhecimento, como Kiyosaki fez quando criança.',
          'Use ativo pra comprar luxo — nunca use salário direto pra comprar coisa cara, use a renda dos ativos.',
          'Busque herói que torna o impossível possível — leia biografia de quem começou do zero e construiu império.',
          'Ensine o que você aprende — quando você ensina, aprende duas vezes.',
        ],
        fechamento:
          'A lição prática final: não espere ter dinheiro pra começar. Comece com o que você tem, onde você está, com o conhecimento que possui. Não existe idade certa, não existe valor mínimo, não existe momento perfeito — o momento perfeito é agora. Como diz Kiyosaki: "A única diferença entre um rico e um pobre é o que eles fazem no seu tempo livre."',
      },
    ],
  }
