import {
  Anchor,
  ArrowLeftRight,
  Baby,
  Banknote,
  BarChart3,
  Bitcoin,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Brain,
  BrainCircuit,
  Briefcase,
  Building,
  Building2,
  Calculator,
  CalendarCheck,
  CalendarClock,
  CandlestickChart,
  CircleDollarSign,
  ClipboardList,
  Coins,
  Compass,
  Crown,
  DollarSign,
  FileBarChart,
  FileLock,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Film,
  Flame,
  Footprints,
  Filter,
  Fuel,
  Gauge,
  Gem,
  GitBranch,
  Globe,
  Globe2,
  GraduationCap,
  Handshake,
  HeartHandshake,
  HelpCircle,
  Hourglass,
  Landmark,
  Layers,
  ListOrdered,
  LayoutGrid,
  Leaf,
  Library,
  LineChart,
  MessageSquare,
  Microscope,
  Mountain,
  MousePointerClick,
  PackagePlus,
  Percent,
  PieChart,
  Plane,
  Radar,
  Receipt,
  RefreshCw,
  Rocket,
  RotateCw,
  Route,
  Ruler,
  Scale,
  Scissors,
  ScrollText,
  SearchCheck,
  Settings2,
  Shapes,
  ShieldAlert,
  ShieldCheck,
  Shuffle,
  Sparkles,
  Trash2,
  Sprout,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Umbrella,
  UserCheck,
  UserCircle,
  Users,
  Vault,
  Wallet,
  Wallet2,
  Workflow,
  Wind,
  Zap,
} from 'lucide-react'
import type { LucideIcon, LucideProps } from 'lucide-react'

/**
 * Registro central de ícones.
 *
 * As telas usavam `import * as Icons from 'lucide-react'` e resolviam por
 * nome em runtime. Isso desliga o tree-shaking: o bundler não tem como saber
 * quais ícones você usa, então empacota a biblioteca inteira (~1.500 ícones).
 * Aqui os ícones realmente usados nos dados são importados nominalmente, e
 * o resto fica de fora do build.
 *
 * Para usar um ícone novo em `iconName`, importe-o e adicione ao mapa abaixo.
 */
const ICONES: Record<string, LucideIcon> = {
  Anchor,
  ArrowLeftRight,
  Baby,
  Banknote,
  BarChart3,
  Bitcoin,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Brain,
  BrainCircuit,
  Briefcase,
  Building,
  Building2,
  Calculator,
  CalendarCheck,
  CalendarClock,
  CandlestickChart,
  CircleDollarSign,
  ClipboardList,
  Coins,
  Compass,
  Crown,
  DollarSign,
  FileBarChart,
  FileLock,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Film,
  Flame,
  Footprints,
  Filter,
  Fuel,
  Gauge,
  Gem,
  GitBranch,
  Globe,
  Globe2,
  GraduationCap,
  Handshake,
  HeartHandshake,
  HelpCircle,
  Hourglass,
  Landmark,
  Layers,
  ListOrdered,
  LayoutGrid,
  Leaf,
  Library,
  LineChart,
  MessageSquare,
  Microscope,
  Mountain,
  MousePointerClick,
  PackagePlus,
  Percent,
  PieChart,
  Plane,
  Radar,
  Receipt,
  RefreshCw,
  Rocket,
  RotateCw,
  Route,
  Ruler,
  Scale,
  Scissors,
  ScrollText,
  SearchCheck,
  Settings2,
  Shapes,
  ShieldAlert,
  ShieldCheck,
  Shuffle,
  Sparkles,
  Trash2,
  Sprout,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Umbrella,
  UserCheck,
  UserCircle,
  Users,
  Vault,
  Wallet,
  Wallet2,
  Workflow,
  Wind,
  Zap,
}

export function getIcon(nome: string | undefined, fallback: LucideIcon = HelpCircle): LucideIcon {
  if (!nome) return fallback
  return ICONES[nome] ?? fallback
}

interface IconProps extends LucideProps {
  name: string | undefined
  fallback?: LucideIcon
}

/** Uso: <Icon name={trilha.iconName} size={18} className="text-accent-cyan" /> */
export default function Icon({ name, fallback = HelpCircle, ...props }: IconProps) {
  const Componente = getIcon(name, fallback)
  return <Componente {...props} />
}

export { ICONES }
