import type { Trilha } from '@/types'

export const TRILHAS: Trilha[] = [
  {
    id: 'fundamentos',
    numero: 1,
    nome: 'Fundamentos e Mentalidade',
    descricao: 'A base de tudo: como você pensa sobre dinheiro',
    iconName: 'Brain',
    cor: '#00D4FF',
    moduloIds: [],
  },
  {
    id: 'economia-mercado',
    numero: 2,
    nome: 'Economia e Mercado',
    descricao: 'Entenda as engrenagens por trás do seu dinheiro',
    iconName: 'TrendingUp',
    cor: '#3B82F6',
    moduloIds: [],
  },
  {
    id: 'renda-fixa-previdencia',
    numero: 3,
    nome: 'Renda Fixa e Previdência',
    descricao: 'Segurança e previsibilidade para seu patrimônio',
    iconName: 'ShieldCheck',
    cor: '#22C55E',
    moduloIds: [],
  },
  {
    id: 'fundos',
    numero: 4,
    nome: 'Fundos',
    descricao: 'Invista em conjunto, com gestão profissional',
    iconName: 'Layers',
    cor: '#8B5CF6',
    moduloIds: [],
  },
  {
    id: 'acoes-bolsa',
    numero: 5,
    nome: 'Ações e Bolsa',
    descricao: 'Torne-se sócio das melhores empresas do país',
    iconName: 'BarChart3',
    cor: '#EC4899',
    moduloIds: [],
  },
  {
    id: 'estrategia-gestao',
    numero: 6,
    nome: 'Estratégia e Gestão',
    descricao: 'Monte e proteja sua carteira como um profissional',
    iconName: 'Target',
    cor: '#FFC93C',
    moduloIds: [],
  },
  {
    id: 'alternativos-derivativos',
    numero: 7,
    nome: 'Alternativos e Derivativos',
    descricao: 'Cripto, ouro, opções e outras classes de ativos',
    iconName: 'Sparkles',
    cor: '#8B5CF6',
    moduloIds: [],
  },
  {
    id: 'vida-financeira',
    numero: 8,
    nome: 'Vida Financeira',
    descricao: 'Liberdade financeira e planejamento de longo prazo',
    iconName: 'Compass',
    cor: '#22C55E',
    moduloIds: [],
  },
  {
    id: 'carreira-negocios',
    numero: 9,
    nome: 'Carreira e Negócios',
    descricao: 'Aumente sua renda ativa e sua capacidade de investir',
    iconName: 'Briefcase',
    cor: '#3B82F6',
    moduloIds: [],
  },
  {
    id: 'cultura-investimentos',
    numero: 10,
    nome: 'Cultura de Investimentos',
    descricao: 'Histórias, livros e casos que formam sua visão de mundo',
    iconName: 'BookOpen',
    cor: '#FFC93C',
    moduloIds: [],
  },
  {
    id: 'geracao-de-receita',
    numero: 11,
    nome: 'Geração de Receita',
    descricao: 'Os números que separam negócios que vendem de negócios que crescem',
    iconName: 'TrendingUp',
    cor: '#EC4899',
    moduloIds: [],
  },
  {
    id: 'cultura-organizacional',
    numero: 12,
    nome: 'Cultura Organizacional',
    descricao: 'O sistema por trás de times que performam sem cobrança constante',
    iconName: 'Users',
    cor: '#8B5CF6',
    moduloIds: [],
  },
  {
    id: 'eficiencia-operacional',
    numero: 13,
    nome: 'Eficiência Operacional',
    descricao: 'O método da Toyota aplicado a qualquer tipo de operação',
    iconName: 'Settings2',
    cor: '#F97316',
    moduloIds: [],
  },
  {
    id: 'gestao-financeira-negocios',
    numero: 14,
    nome: 'Gestão Financeira de Negócios',
    descricao: 'Lucro no papel não paga conta — o arsenal de quem decide com números',
    iconName: 'LineChart',
    cor: '#22C55E',
    moduloIds: [],
  },
]
